# Generated by Django 3.0.4 on 2020-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
